export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP'
export const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const POST_EVENT = 'POST_EVENT';
export const MENU_UPDATE = 'MENU_UPDATE';
export const EVENT_VIEW = 'EVENT_VIEW';

