export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const GET_OWNER = 'GET_OWNER';
export const UPDATE_OWNER = 'UPDATE_OWNER';