export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const GET_OWNER = 'GET_OWNER';
export const UPDATE_OWNER = 'UPDATE_OWNER';